FROM jupyter/pyspark-notebook:latest

USER root

# Installer kafka-python et requests
RUN pip install kafka-python requests

USER jovyan

COPY notebooks/ /home/jovyan/work/notebooks/
WORKDIR /home/jovyan/work
